config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'movies#index'

  get 'transactions/dashboard', to: 'transactions#dashboard'

  resources :movies, only: [:index, :show]
  resources :showings, only: [:show]
  resources :transactions, only: [:create, :show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	validates_presence_of :title
	has_many :showings
	has_many :transactions, through: :showings

  scope :active_movie, -> (start_date, end_date) { joins(:showings).where('showings.date >= ? AND showings.date <= ?', start_date, end_date)}
end

app/models/showing.rb
class Showing < ActiveRecord::Base
	belongs_to :movie
	has_many :transactions
  validates_presence_of :date, :time, :capacity, :price
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
	validates_presence_of :quantity, :cost
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255}, format: { with: VALID_EMAIL_REGEX }
	validates :first_name, presence: true, length: { maximum: 50}
	validates :last_name, presence: true, length: { maximum: 50}

	belongs_to :showing

	def self.active_card(exp_date, cc_number)
		exp_date != '' &&
		Date.strptime(exp_date, '%Y-%m') > Date.today &&
		CreditCardValidations::Luhn.valid?(cc_number) &&
		CreditCardValidations::Detector.new(cc_number).valid?
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/concerns/transactions_controller.rb
class TransactionsController < ApplicationController

	def new
		
	end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	include ApplicationHelper

	def index
		@movie_list = Movie.includes(:showings).active_movie(Date.new(2018, 4 ,12), Date.new(2018, 4, 17)).uniq.map do |movie|
			{
				movie: movie,
				showings: movie.showings
			}
		end
	end

	def show
		@movie = Movie.find(params[:id])
		@transactions = @movie.transactions.includes(:showing).map do |transaction|
			{
				trans: transaction,
				showing: transaction.showing
			}
		end
	end
end

app/controllers/showings_controller.rb
class ShowingsController < ApplicationController
  include ApplicationHelper

	def show
		@showing = Showing.find(params[:id])
		@movie = Movie.find_by(id: @showing.movie_id)
		@transaction = Transaction.new
		@tickets_sold = @showing.transactions.sum(:quantity)
	end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
	include ApplicationHelper

	def create
		if Transaction.active_card(params[:credit_card_expiration], params[:credit_card_number])
			@transaction = TransactionCreateService.new(transaction_params).create
			if @transaction
				ConfirmationMailer.with(transaction: @transaction).receipt_email.deliver_now
				render 'show'
			else
				flash[:notice] = "There is an error with your name or email"
				redirect_to showing_path(params[:id])
			end
		else
			flash[:notice] = "There is an error with your credit card information"
			redirect_to showing_path(params[:transaction][:showing_id])
		end
	end

	def show
		@transaction = Transaction.find(params[:id])
	end

	def index
		@all_transactions = Transaction.includes(showing: :movie).all.map do |transaction|
			{
				transaction: transaction,
				showing: transaction.showing,
				movie: transaction.showing.movie
			}
		end
	end

	def dashboard
		dash_services = DashboardService.new
		@total_rev = dash_services.total_rev
		@daily_sales = dash_services.daily_sales
		@hourly_sales = dash_services.hourly_sales
		@movie_sales = dash_services.movie_sales
	end

	private

	def transaction_params
		params.require(:transaction).permit(:email, :first_name, :last_name, :showing_id, :quantity)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_dollar(val)
    ActiveSupport::NumberHelper.number_to_currency(val)
  end

  def format_date(val)
    return unless val
    val.strftime('%-m/%-d/%Y').to_s
  end

  def format_showing_date(val)
    return unless val
    val.strftime('%A, %B %e')
  end
end

app/helpers/transaction_helper.rb
module TransactionHelper


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieApp</title>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>
  <header>
  	<div>
  		<%= link_to 'Movie Listings', root_path%>
  	</div>
    <div>
      <%= link_to 'Sales Dashboard', transactions_dashboard_path%>
    </div>
  </header>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<h1>Movie Index Page</h1>

<nav>
	<div class='date'>
		<%= format_date(Date.new(2018, 4, 12)) %>
	</div>
	<div class='date'>
		<%= format_date(Date.new(2018, 4, 13)) %>
	</div>
	<div class='date'>
		<%= format_date(Date.new(2018, 4, 14)) %>
	</div>
	<div class='date'>
		<%= format_date(Date.new(2018, 4, 15)) %>
	</div>
	<div class='date'>
		<%= format_date(Date.new(2018, 4, 16)) %>
	</div>
	<div class='date'>
		<%= format_date(Date.new(2018, 4, 17)) %>
	</div>
</nav>

<div class='movie'>
	<% @movie_list.each do |movie| %>

		<div class='title'>
			<h2><%= movie[:movie].title %></h2>
		</div>

		<div class='showings'>
			<% movie[:showings].each do |showing| %>
				<span class=<%= format_date(showing.date) %>>
					<%= link_to showing.time, showing %>
				</span>
			<% end %>
		</div>
	<% end %>
</div>

app/views/movies/show.html.erb
<h1><%= @movie.title %> Sales</h1>


<div id='headings'>
	<div class='cell'>
		Email:
	</div>
	<div class='cell'>
		Date:
	</div>
	<div class='cell'>
		Time:
	</div>
	<div class='cell'>
		Tickets Purchased:
	</div>
	<div class='cell'>
		Subtotal:
	</div>
</div>

<div id='data'>
	<% @transactions.each do |transaction| %>
	<div class='row'>
		<div class='cell'>
			<%= transaction[:trans].email %>
		</div>
		<div class='cell'>
			<%= transaction[:showing].date %>
		</div>
		<div class='cell'>
			<%= transaction[:showing].time %>
		</div>
		<div class='cell'>
			<%= transaction[:trans].quantity %>
		</div>
		<div class='cell'>
			<%= format_dollar(transaction[:trans].cost) %>
		</div>


	</div>

	<% end %>
</div>

app/views/showings/show.html.erb
<h1><%= @movie.title %></h1>

<h4><%= format_showing_date(@showing.date) %> <%= @showing.time %></h4>

<% if @showing.capacity - @tickets_sold <= 0 %>

	<div id='sold-out'>Sold Out!</div>

<% else %>

	<h3>Tickets Remaining: <%= @showing.capacity - @tickets_sold%></h3>



	<% flash.each do |name, msg| %>
      <ul>
        <li><%= msg %></li>
      </ul>
    <% end %>

	<%= form_for @transaction do |f| %>

	<p>
		<%= f.label :email %>
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :first_name %>
		<%= f.text_field :first_name %>
	</p>
	<p>
		<%= f.label :last_name %>
		<%= f.text_field :last_name %>
	</p>
	<p>
		<%= f.label :quantity %>
		<%= f.select :quantity, options_for_select([*1..@showing.capacity - @tickets_sold], 1)%>
		<%= format_dollar(@showing.price) %>/ticket
	<p>
		Credit Card Number <input type="text" name="credit_card_number">
	</p>
	<p>
		Credit Card Expiration <input min=<%= Date.today %> type="month" name="credit_card_expiration">
	</p>
	<%= f.hidden_field :showing_id, :value => @showing.id %>
	<p>
		<%=f.submit%>
	</p>

	<% end %>
<% end %>

app/views/transactions/dashboard.html.erb
<h1>Dashboard</h1>

<div id='dash'>
	<div id='hero'>
		<h2>Total Revenue</h2>
		<h2><%= format_dollar(@total_rev) %></h2>
		<%= link_to 'Click to view all Transactions', transactions_path %>
	</div>


	<div class='cols'>
		<h2>Daily Sales</h2>
		<% @daily_sales.each_pair do |key, value| %>
			<div>
				<%= key %>: <%= format_dollar(value[:sales]) %>
			</div>
		<% end %>
	</div>

	<div class='cols'>
		<h2>Hourly Sales</h2>
		<% @hourly_sales.each_pair do |key, value| %>
			<div>
				<%= key %>: <%= format_dollar(value[:sales]) %>
			</div>
		<% end %>
	</div>


	<div class='cols'>
		<h2>Movie Sales</h2>
		<p id='note'>(Select Movie Title to view transactions)</p>

		<% @movie_sales.each_pair do |key, value| %>
			<div class='movie-row'>
				<%= link_to key, movie_path(value[:id]) %>: <%= format_dollar(value[:sales]) %>
			</div>

		<% end %>
	</div>
</div>

app/views/transactions/index.html.erb
<h1>Transaction Log</h1>

<div id='headings'>
	<div class='cell'>
		Movie:
	</div>
	<div class='cell'>
		Email:
	</div>
	<div class='cell'>
		Date:
	</div>
	<div class='cell'>
		Time:
	</div>
	<div class='cell'>
		Tickets Purchased:
	</div>
	<div class='cell'>
		Subtotal:
	</div>
</div>

<div id='data'>
	<% @all_transactions.each do |transaction| %>
	<div class='row'>
		<div class='cell'>
			<%= transaction[:movie].title %>
		</div>
		<div class='cell'>
			<%= transaction[:transaction].email %>
		</div>
		<div class='cell'>
			<%= transaction[:showing].date %>
		</div>
		<div class='cell'>
			<%= transaction[:showing].time %>
		</div>
		<div class='cell'>
			<%= transaction[:transaction].quantity %>
		</div>
		<div class='cell'>
			<%= format_dollar(transaction[:transaction].cost) %>
		</div>


	</div>

	<% end %>
</div>

app/views/transactions/show.html.erb
<h1>Thank You For Your Purchase</h1>

<div id='confirm'>
	<div>
		Your purchase of <%= @transaction.quantity %> tickets has been confirmed.
	</div>

	<div>
		Your receipt will be emailed to <%= @transaction.email %>
	</div>

	<div>
		Your card will be charged <%= format_dollar(@transaction.cost) %>
	</div>
</div>